app/models/LoginForm.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import InputRequired, Length

# Handles login functionality for the admin routes
class LoginForm(FlaskForm):
    username = StringField(validators=[InputRequired(), Length(
        min=4, max=20)], render_kw={"placeholder": "Username"})

    password = PasswordField(validators=[InputRequired(), Length(
        min=4, max=20)], render_kw={"placeholder": "Password"})

    submit = SubmitField("Login")

app/models/RegisterForm.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import InputRequired, Length, ValidationError
from app.models import AdminUser
from app.db import get_db

# Handles admin registration for the admin routes
class RegisterForm(FlaskForm):
    username = StringField(validators=[InputRequired(), Length(
        min=4, max=20)], render_kw={"placeholder": "Username"})

    password = PasswordField(validators=[InputRequired(), Length(
        min=4, max=20)], render_kw={"placeholder": "Password"})

    submit = SubmitField("Register")

    def validate_username(self, username):
        db = get_db()
        existing_admin_username = db.query(AdminUser).filter_by(username = username).first()

        if existing_admin_username:
            raise ValidationError(
                "That username already exists. Please choose a different one."
            )

app/routes/admin.py
from flask import Blueprint, render_template, url_for, redirect
from app.models import AdminUser, LoginForm, RegisterForm
from app.db import get_db
from flask_login import login_user, login_required, logout_user
import bcrypt

# Uses /api endpoint for all of these api routes
bp = Blueprint('administrator', __name__, url_prefix='/administrator')

# Generates salt used to hash password with bcrypt
salt = bcrypt.gensalt()

# Route for the homepage
@bp.route('/')
def home():
    return render_template('home.html')

# Routes to login with username and password
@bp.route('/login', methods = ['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        db = get_db();
        user = db.query(AdminUser).filter_by(username=form.username.data).first()
        if user:
            if bcrypt.checkpw(form.password.data.encode('utf-8'), user.password.encode('utf-8')):
                login_user(user)
                return redirect(url_for('admin.index'))
        else:
            return redirect (url_for('incorrect'))
    return render_template('login.html', form = form)

# Routes for incorrect login information
@bp.route('/incorrect', methods = ['GET', 'POST'])
def incorrect():
    return render_template ('incorrect.html')

# Routes for registering a new admin user
@bp.route('/register', methods = ['GET', 'POST'])
def register():
    form = RegisterForm()

    if form.validate_on_submit():
        db = get_db();
        hashed_password = bcrypt.hashpw(form.password.data.encode('utf-8'), salt)
        print(hashed_password)
        new_admin = AdminUser(username=form.username.data, password=hashed_password)
        db.add(new_admin)
        db.commit()
        return redirect(url_for('administrator.login'))

    return render_template('register.html', form = form)

# Routes to enter the dashboard
@bp.route('/dashboard', methods = ['GET', 'POST'])
@login_required
def dashboard():
    return render_template('dashboard.html')

# Routes to logout
@bp.route('/logout', methods = ['GET', 'POST'])
@login_required
def logout():
    logout_user()
    return render_template('dashboard.html')

app/templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>

    <title>Dashboard</title>
</head>
<body>

    <h1> You have been logged out.</h1>
    <a href = "{{url_for('administrator.login')}}">Click here to log back in.</a><p></p>
    <a href = "{{url_for('administrator.home')}}">Click here to return to the home screen.</a>
    
    
</body>
</html>

app/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Home</title>
</head>

<body>
    <h1>Geek Text - Bookstore API Home</h1>
    <a href="{{url_for('administrator.login')}}">Login Page</a><br><p></p>
    <a href="{{url_for('administrator.register')}}">Register Page</a><br>
</body>

</html>

app/templates/incorrect.html
<!DOCTYPE html>
<html lang="en">
<body>
    <h1> The username and/or password you entered is incorrect or has not been registered.</h1>
    <a href = "{{url_for('administrator.login')}}">Click here to try again.</a><p></p>
    <a href = "{{url_for('administrator.register')}}">Click here to register.</a>
    
</body>
</html>

app/templates/index.html
<extends 'admin/master.html'></extends>
<body >
    <p> This is where admins will be able to add books!</p>
</body>

app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Login</title>
</head>

<body>
    <h1>Login Page</h1>

    <form method = "POST" action = "">
        {{ form.hidden_tag() }}
        {{ form.username }}
        {{ form.password }}
        {{ form.submit }}

    </form>
    <p></p>
    <a href="{{url_for('administrator.register')}}">Don't have an account? Sign up</a><br>
</body>
</html>

app/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Register</title>
</head>

<body>
    <h1>Register Page</h1>

    <form method = "POST" action = "">
        {{ form.hidden_tag() }}
        {{ form.username }}
        {{ form.password }}
        {{ form.submit }}

    </form>
    <p>
    </p>
    <a href="{{url_for('administrator.login')}}">Already have an account? Login</a><br>
</body>
</html>